# config.py

import os

KNOWN_FACES_DIR = "faces"
UNKNOWN_SAVE_DIR = "logs/unknown_faces"
os.makedirs(UNKNOWN_SAVE_DIR, exist_ok=True)

PROCESS_EVERY_N_FRAMES = 7
FRAME_HISTORY = 5
DECISION_THRESHOLD = 0.7
DISAPPEAR_FRAMES = 30
TOLERANCE = 0.45

ARDUINO_PORT = "COM3"
ARDUINO_BAUD = 9600

ALERT_BEEP_FREQ = 1000
ALERT_BEEP_DUR = 300
